const std = @import("std");
const ai = @import("forge-ai");
const workspace = @import("forge-workspace");
const kernel = @import("forge-kernel");
const workspace_cmd = @import("workspace_cmd.zig");

pub const Mode = enum {
    ask,
    plan,
};

pub const Result = struct {
    run_id: []const u8,
    proposal_rel: []const u8,
};

pub fn generateAndPersist(
    allocator: std.mem.Allocator,
    io: std.Io,
    opened: workspace_cmd.OpenedWorkspace,
    mode: Mode,
    intent: []const u8,
    files: []const []const u8,
    provider_response: []const u8,
) !Result {
    var ctx_builder = try ai.context_loader.build(allocator, io, opened.root, .{
        .intent = intent,
        .explicit_files = files,
    });
    defer ctx_builder.deinit();

    var fake = ai.fake_provider.FakeProvider.init(provider_response);
    const provider = fake.providerInterface();
    const meta = provider.metadata();

    var planner = ai.planner.Planner.init(allocator, provider, &ctx_builder);

    var response = std.Io.Writer.Allocating.init(allocator);
    defer response.deinit();

    var cancel_src = try kernel.cancellation.CancellationTokenSource.init(allocator);
    defer cancel_src.deinit();
    const token = cancel_src.getToken();

    try planner.plan(&response.writer, &token);

    const proposal_body = response.writer.buffer[0..response.writer.end];
    const timestamp_ms = std.Io.Timestamp.now(io, .real).toMilliseconds();
    const run_id = try ai.run_record.makeRunId(allocator, timestamp_ms);
    errdefer allocator.free(run_id);

    try workspace.history.ensureLayout(io, opened.root);

    var proposal_path_buf: [std.fs.max_path_bytes]u8 = undefined;
    const proposal_rel = try std.fmt.bufPrint(&proposal_path_buf, ".forge/proposals/{s}.json", .{run_id});
    try workspace.atomic.replaceFile(io, opened.root, try workspace.WorkspacePath.parse(proposal_rel), proposal_body);

    const initial_state: ai.run_record.State = switch (mode) {
        .ask => .proposed,
        .plan => .planning,
    };

    const record = ai.run_record.Record{
        .run_id = run_id,
        .surface = .cli,
        .intent = intent,
        .state = initial_state,
        .proposal_path = proposal_rel,
        .provider_id = meta.provider_name,
        .model_id = meta.model_name,
        .timestamp_ms = timestamp_ms,
    };

    const json_body = try ai.run_record.formatJson(allocator, record);
    defer allocator.free(json_body);
    try workspace.runs.persistRun(io, opened.root, run_id, json_body);

    const index_line = try ai.run_record.formatIndexLine(allocator, record);
    defer allocator.free(index_line);
    try workspace.runs.appendIndex(allocator, io, opened.root, index_line);

    const owned_run_id = try allocator.dupe(u8, run_id);
    const owned_proposal_rel = try allocator.dupe(u8, proposal_rel);

    return .{ .run_id = owned_run_id, .proposal_rel = owned_proposal_rel };
}

pub const default_ask_response =
    \\{"files":[{"path":"notes.txt","operation":"create","edits":[{"start":0,"end":0,"replacement":"generated by forge ask\n"}]}]}
;

pub const default_plan_response =
    \\{"files":[{"path":"plan.txt","operation":"create","edits":[{"start":0,"end":0,"replacement":"planned change\n"}]}]}
;
