const std = @import("std");
const ai = @import("forge-ai");
const workspace = @import("forge-workspace");
const kernel = @import("forge-kernel");
const args_mod = @import("args.zig");
const workspace_cmd = @import("workspace_cmd.zig");

pub fn run(allocator: std.mem.Allocator, io: std.Io, parsed: args_mod.CliArgs, writer: *std.Io.Writer) !u8 {
    if (parsed.positional.len == 0) {
        try writer.writeAll("error: ask requires an intent\n");
        return 2;
    }

    const intent = parsed.positional[0];

    var opened = try workspace_cmd.OpenedWorkspace.open(allocator, io, parsed);
    defer opened.close(io);

    if (!parsed.flags.quiet and !parsed.flags.json) {
        try writer.print("Asking: {s}\n", .{intent});
        try writer.writeAll("Building context...\n");
    }

    var ctx_builder = try ai.context_loader.build(allocator, io, opened.root, .{
        .intent = intent,
        .explicit_files = parsed.flags.files,
    });
    defer ctx_builder.deinit();

    const timestamp_ms = std.Io.Timestamp.now(io, .real).toMilliseconds();
    const run_id = try ai.run_record.makeRunId(allocator, timestamp_ms);
    defer allocator.free(run_id);

    var fake = ai.fake_provider.FakeProvider.init(
        \\{"files":[{"path":"notes.txt","operation":"create","edits":[{"start":0,"end":0,"replacement":"generated by forge ask\n"}]}]}
    );
    const provider = fake.providerInterface();
    const meta = provider.metadata();

    var planner = ai.planner.Planner.init(allocator, provider, &ctx_builder);

    var response = std.Io.Writer.Allocating.init(allocator);
    defer response.deinit();

    var cancel_src = try kernel.cancellation.CancellationTokenSource.init(allocator);
    defer cancel_src.deinit();
    const token = cancel_src.getToken();

    if (!parsed.flags.quiet and !parsed.flags.json) {
        try writer.writeAll("Invoking model...\n");
    }

    planner.plan(&response.writer, &token) catch |err| {
        try writer.print("error: ask failed: {}\n", .{err});
        return 1;
    };

    const proposal_body = response.writer.buffer[0..response.writer.end];

    try workspace.history.ensureLayout(io, opened.root);

    var proposal_path_buf: [std.fs.max_path_bytes]u8 = undefined;
    const proposal_rel = try std.fmt.bufPrint(&proposal_path_buf, ".forge/proposals/{s}.json", .{run_id});
    try workspace.atomic.replaceFile(io, opened.root, try workspace.WorkspacePath.parse(proposal_rel), proposal_body);

    const record = ai.run_record.Record{
        .run_id = run_id,
        .surface = .cli,
        .intent = intent,
        .state = .proposed,
        .proposal_path = proposal_rel,
        .provider_id = meta.provider_name,
        .model_id = meta.model_name,
        .timestamp_ms = timestamp_ms,
    };

    const json_body = try ai.run_record.formatJson(allocator, record);
    defer allocator.free(json_body);
    try workspace.runs.persistRun(io, opened.root, run_id, json_body);

    const index_line = try ai.run_record.formatIndexLine(allocator, record);
    defer allocator.free(index_line);
    try workspace.runs.appendIndex(allocator, io, opened.root, index_line);

    if (parsed.flags.json) {
        try writer.print(
            "{{\"status\":\"ok\",\"type\":\"ask\",\"run_id\":\"{s}\",\"proposal_path\":\"{s}\",\"state\":\"proposed\"}}\n",
            .{ run_id, proposal_rel },
        );
    } else {
        try writer.print("Proposal saved to {s}\n", .{proposal_rel});
        try writer.print("Run record: .forge/runs/{s}.json\n", .{run_id});
        try writer.writeAll("Review with: forge diff <proposal> --workspace <path>\n");
    }

    return 0;
}
