const std = @import("std");

pub const BottomPanelMode = enum { output, problems, terminal, debug_console };

pub const Command = union(enum) {
    open_file: []const u8,
    activate_tab: usize,
    close_tab: usize,
    close_active_tab: void,
    close_all_tabs: void,
    save_active: void,
    explorer_toggle: []const u8,
    explorer_select: []const u8,
    explorer_create_file: []const u8,
    explorer_create_folder: []const u8,
    explorer_rename: struct {
        path: []const u8,
        new_name: []const u8,
    },
    explorer_delete_selected: void,
    explorer_begin_rename: void,
    run_extension_command: []const u8,
    reload_extensions: void,
    refresh_explorer: void,
    run_task: []const u8,
    check_external_conflicts: void,
    reload_active_from_disk: void,
    dismiss_external_conflict: void,
    restore_recovery_snapshots: void,
    discard_recovery_snapshots: void,
    agent_set_mode: @import("../agent/session.zig").Mode,
    agent_submit: void,
    agent_cancel: void,
    agent_apply: void,
    agent_reject: void,
    agent_select_run: usize,
    agent_refresh_runs: void,
    agent_add_scope: []const u8,
    agent_remove_scope: []const u8,
    agent_clear_scope: void,
    agent_scope_picker_open: void,
    agent_scope_picker_close: void,
    agent_scope_picker_select: void,
    set_shell_mode: @import("../ui/layout.zig").ShellMode,
    toggle_shell_mode: void,
    reload_theme: void,
    set_sidebar_view: @import("../ui/sidebar_view.zig").SidebarView,
    extension_toggle: usize,
    open_extensions_dir: []const u8,
    install_marketplace_extension: []const u8,
    apply_extension_theme: []const u8,
    set_extensions_panel_mode: @import("../ui/extensions_panel.zig").PanelMode,
    search_run: void,
    git_refresh: void,
    uninstall_extension: []const u8,
    extensions_show_detail: usize,
    extensions_back_from_detail: void,
    set_bottom_panel_mode: BottomPanelMode,
    terminal_submit: void,
    debug_toggle_breakpoint: void,
    debug_clear_breakpoints: void,
    debug_run_launch: usize,
    debug_clear_console: void,
    editor_completion: void,
    palette_open: void,
    palette_close: void,
};

pub const Event = union(enum) {
    file_opened: []const u8,
    file_saved: []const u8,
    explorer_refreshed: void,
    extension_loaded: []const u8,
    status_message: []const u8,
    task_output: []const u8,
    task_finished: i32,
};

pub fn freeCommand(allocator: std.mem.Allocator, command: Command) void {
    switch (command) {
        .open_file, .explorer_toggle, .explorer_select => |path| allocator.free(path),
        .explorer_create_file, .explorer_create_folder, .run_task, .run_extension_command, .open_extensions_dir, .install_marketplace_extension, .apply_extension_theme, .uninstall_extension => |owned| allocator.free(owned),
        .explorer_rename => |payload| allocator.free(payload.new_name),
        else => {},
    }
}
