const std = @import("std");

pub const BottomPanelMode = enum { output, problems, terminal, debug_console, debug_variables, debug_callstack };

pub const Command = union(enum) {
    open_file: []const u8,
    activate_tab: usize,
    close_tab: usize,
    close_active_tab: void,
    close_all_tabs: void,
    save_active: void,
    explorer_toggle: []const u8,
    explorer_select: []const u8,
    explorer_create_file: []const u8,
    explorer_create_folder: []const u8,
    explorer_rename: struct {
        path: []const u8,
        new_name: []const u8,
    },
    explorer_delete_selected: void,
    explorer_begin_rename: void,
    run_extension_command: []const u8,
    reload_extensions: void,
    refresh_explorer: void,
    run_task: []const u8,
    check_external_conflicts: void,
    reload_active_from_disk: void,
    dismiss_external_conflict: void,
    restore_recovery_snapshots: void,
    discard_recovery_snapshots: void,
    agent_set_mode: @import("../agent/session.zig").Mode,
    agent_submit: void,
    agent_edit_selection: void,
    agent_cancel: void,
    agent_apply: void,
    agent_rollback: void,
    agent_dismiss_apply: void,
    agent_approve_spec: void,
    agent_approve_tool: void,
    agent_reject_tool: void,
    agent_continue_session: void,
    agent_dismiss_resume: void,
    agent_reject: void,
    agent_show_review: void,
    agent_toggle_step: usize,
    agent_select_run: usize,
    agent_refresh_runs: void,
    agent_add_scope: []const u8,
    agent_remove_scope: []const u8,
    agent_clear_scope: void,
    agent_scope_picker_open: void,
    agent_scope_picker_close: void,
    agent_toggle_mode_menu: void,
    agent_toggle_model_menu: void,
    agent_close_menus: void,
    agent_set_model: usize,
    agent_remove_attachment: usize,
    agent_toggle_context_inspector: void,
    agent_scope_picker_select: void,
    set_shell_mode: @import("../ui/core/layout.zig").ShellMode,
    toggle_shell_mode: void,
    reload_theme: void,
    set_sidebar_view: @import("../ui/sidebar/sidebar_view.zig").SidebarView,
    extension_toggle: usize,
    open_extensions_dir: []const u8,
    install_marketplace_extension: []const u8,
    apply_extension_theme: []const u8,
    set_extensions_panel_mode: @import("../ui/sidebar/extensions_panel.zig").PanelMode,
    search_run: void,
    git_refresh: void,
    uninstall_extension: []const u8,
    extensions_show_detail: usize,
    extensions_back_from_detail: void,
    set_bottom_panel_mode: BottomPanelMode,
    terminal_submit: void,
    terminal_new: void,
    terminal_close: void,
    terminal_next: void,
    terminal_prev: void,
    terminal_activate: usize,
    debug_toggle_breakpoint: void,
    debug_clear_breakpoints: void,
    debug_run_launch: usize,
    debug_clear_console: void,
    debug_continue: void,
    debug_step_over: void,
    debug_step_into: void,
    debug_step_out: void,
    debug_stop: void,
    editor_completion: void,
    editor_find: void,
    editor_replace: void,
    editor_goto_line: void,
    editor_find_next: void,
    editor_find_prev: void,
    editor_find_close: void,
    editor_redo: void,
    editor_undo: void,
    editor_scroll_to_cursor: void,
    editor_go_to_definition: void,
    editor_find_references: void,
    editor_rename_symbol: void,
    editor_format_document: void,
    editor_split_right: void,
    editor_close_split: void,
    editor_accept_inline_edit: void,
    editor_reject_inline_edit: void,
    rename_accept: void,
    rename_reject: void,
    references_goto: usize,
    problems_goto: usize,
    completion_accept: void,
    completion_dismiss: void,
    save_session_state: void,
    restore_session_state: void,
    settings_reload: void,
    settings_toggle_word_wrap: void,
    open_recent_workspace: usize,
    problem_quick_fix: void,
    debug_stack_goto: usize,
    debug_copy_variable: usize,
    toggle_sidebar: void,
    toggle_bottom_panel: void,
    toggle_agent_panel: void,
    focus_agent: void,
    nav_back: void,
    nav_forward: void,
    close_ai_settings: void,
    close_proposal_review: void,
    open_ai_settings: void,
    ai_open_forge_toml: void,
    ai_open_mcp_config: void,
    ai_toggle_mcp: void,
    ai_refresh_mcp: void,
    palette_open: void,
    palette_close: void,
};

pub const Event = union(enum) {
    file_opened: []const u8,
    file_saved: []const u8,
    explorer_refreshed: void,
    extension_loaded: []const u8,
    status_message: []const u8,
    task_output: []const u8,
    task_finished: i32,
};

pub fn freeCommand(allocator: std.mem.Allocator, command: Command) void {
    switch (command) {
        .open_file, .explorer_toggle, .explorer_select => |path| allocator.free(path),
        .explorer_create_file, .explorer_create_folder, .run_task, .run_extension_command, .open_extensions_dir, .install_marketplace_extension, .apply_extension_theme, .uninstall_extension => |owned| allocator.free(owned),
        .explorer_rename => |payload| allocator.free(payload.new_name),
        else => {},
    }
}
